FROM pingcap/alpine-glibc:alpine-3.14.6-gcompat
MAINTAINER cybwan <baili@flomesh.io>

RUN apk update \
    && apk upgrade \
    && apk add --no-cache tcpdump tzdata curl wget lsof iotop bind-tools strace file iproute2 drill \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime  \
    && echo "Asia/Shanghai">>/etc/timezone \
    && rm -rf /var/cache/apk/*
